creation_rules:
- path_regex: .*/.*\.yaml$
  encrypted_regex: ^(\s*[A-Za-z_-]+\s*=\s*")[^"]*(")|^(.*\s*:\s*)[^{][^"\n\r]*([\n\r]|$)
  age: age1zka66l5vjdc7c30tyne0w3asdvhrja63r4yx05693am7lmqyvqvqfwkmmc
- path_regex: .*/.*\.txt$
  encrypted_regex: ^(.*)$
  age: age1zka66l5vjdc7c30tyne0w3asdvhrja63r4yx05693am7lmqyvqvqfwkmmc