services:
  swag:
    image: linuxserver/swag:latest
    environment:
      - URL=onlychicks.tv
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false
      - STAGING=false
      - SUBDOMAINS=www
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Brisbane
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config:/config
      - ./config/proxy-confs:/config/nginx/proxy-confs
    networks:
      - videofeed

  rtsp-proxy:
    image: bluenviron/mediamtx:latest
    ports:
      - "8888:8888"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
    networks:
      - videofeed

  chicky-control:
    build: ./chicky-control
    ports:
      - "3000:3000"
    volumes:
      - ./chicky-control:/usr/src/app:rw
    network_mode: host

networks:
  videofeed:
    driver: bridge
