version: '2.1'

services:
  chicky:
    build: .
    privileged: true
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      REMOTE_WS_URL: "wss://onlychicks.tv"
      AUTH_TOKEN: "${AUTH_TOKEN}"
      SERVO1_PIN: "15"
      SERVO2_PIN: "14"
      DEBUG: "false"
      ALLOWED_START_HOUR: "5"  # 5am AEST
      ALLOWED_END_HOUR: "19"   # 7pm AEST
      TIMEZONE_OFFSET: "10"    # AEST+10
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
      io.balena.features.supervisor-api: '1'
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
