version: '2'

services:
  chicky:
    build: .
    privileged: true
    restart: always
    network_mode: host
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    environment:
      - PORT=3000
      - REMOTE_SERVER=${REMOTE_SERVER}
      - AUTH_TOKEN=${CHICKY_AUTH_TOKEN}
