name: Deploy chicky to Balena

on:
  push:
    paths:
      - 'v2/chicky/**'

jobs:
  version-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
        
      # Deploy to Balena (will handle versioning automatically)
      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        id: balena-deploy
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: ${{ secrets.BALENA_FLEET }}
          environment: balena-cloud.com
          create_tag: true
          source: v2/chicky
          layer_cache: true
          debug: false

      # Log release information
      - name: Log release information
        run: |
          echo "Built release ID ${{ steps.balena-deploy.outputs.release_id }}"
          echo "Release version ${{ steps.balena-deploy.outputs.version }}"