name: Deploy chicky to Balena

on:
  push:
    paths:
      - 'chicky/**'

jobs:
  version-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Bump version in package.json
      - name: Bump version in package.json
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          PACKAGEJSON_DIR: 'chicky'
          skip-push: 'true' # Let the next action push the changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Manually update version in balena.yml
      - name: Update version in balena.yml
        run: |
          # Install yq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          # Update version in balena.yml
          yq -i '.version = "${{ steps.version-bump.outputs.newTag }}"' chicky/balena.yml
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chicky/balena.yml
          git commit -m "ci: update package.json & balena.yml version to ${{ steps.version-bump.outputs.newTag }}"
          git push

      # Deploy to Balena
      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        id: balena-deploy
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: ${{ secrets.BALENA_FLEET }}
          environment: balena-cloud.com
          create_tag: true
          source: chicky
          layer_cache: true
          debug: false

      # Log release information
      - name: Log release information
        run: |
          echo "Built release ID ${{ steps.balena-deploy.outputs.release_id }}"
          echo "Release version ${{ steps.balena-deploy.outputs.version }}"